### ISSUE TITLE
Keep getting error "Cannot find module 'big-integer'"

### ISSUE THREAD

**Issue by Solexplorer** [EYBlockchain/nightfall#15]
Hi,

I have installed nodejs with the version 10.15.3 as specified in the readme and I am running on Ubuntu 18.04.

When doing npm install it installs the packages correctly:
`root@vultr:~/nightfall/zkp# npm install`

But when I try to run:
`root@vultr:~/nightfall/zkp# npm run setup`

I get this error: 
```
> zkp@1.0.0 setup /root/nightfall/zkp
> NODE_ENV=setup npx babel-node code/index.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'big-integer'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.require (/root/nightfall/zkp-utils/index.js:10:12)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Module._compile (/root/nightfall/zkp/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Object.newLoader [as .js] (/root/nightfall/zkp/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zkp@1.0.0 setup: `NODE_ENV=setup npx babel-node code/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zkp@1.0.0 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-01T14_51_31_569Z-debug.log

```

I have tried installing the module given but I keep getting the error.

Here is the full log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/root/.nvm/versions/node/v10.16.0/bin/node',
1 verbose cli   '/root/.nvm/versions/node/v10.16.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'setup' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose run-script [ 'presetup', 'setup', 'postsetup' ]
5 info lifecycle zkp@1.0.0~presetup: zkp@1.0.0
6 info lifecycle zkp@1.0.0~setup: zkp@1.0.0
7 verbose lifecycle zkp@1.0.0~setup: unsafe-perm in lifecycle true
8 verbose lifecycle zkp@1.0.0~setup: PATH: /root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/nightfall/zkp/node_modules/.bin:/root/.nvm/versions/node/v10.16.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle zkp@1.0.0~setup: CWD: /root/nightfall/zkp
10 silly lifecycle zkp@1.0.0~setup: Args: [ '-c', 'NODE_ENV=setup npx babel-node code/index.js' ]
11 silly lifecycle zkp@1.0.0~setup: Returned: code: 1  signal: null
12 info lifecycle zkp@1.0.0~setup: Failed to exec setup script
13 verbose stack Error: zkp@1.0.0 setup: `NODE_ENV=setup npx babel-node code/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid zkp@1.0.0
15 verbose cwd /root/nightfall/zkp
16 verbose Linux 4.15.0-50-generic
17 verbose argv "/root/.nvm/versions/node/v10.16.0/bin/node" "/root/.nvm/versions/node/v10.16.0/bin/npm" "run" "setup"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error zkp@1.0.0 setup: `NODE_ENV=setup npx babel-node code/index.js`
22 error Exit status 1
23 error Failed at the zkp@1.0.0 setup script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by iAmMichaelConnor** [comment]
It looks like you need to do an ‘npm ci’ in the zkp-demo folder too. That seems to be where it can’t find the big integer library.
We’ve found that ‘npm ci’ is preferable to doing ‘npm install’ in folders, because it preserves the package-lock.json from the repo.

**Comment by asishap** [comment]
@Solexplorer 
I think you missed out one of the steps in `ReadMe` file. Please run the following command in `zkp-utils` folder.
```
cd zkp-utils
npm ci
``` 
As mentioned in @iAmMichaelConnor comment, preffer to run `npm ci` rather than `npm install`

**Comment by Westlad** [comment]
@Solexplorer If you have done npm install rather than npm ci, I recommend you do a git reset --hard from the root of the repo and go again.  That's because npm install will over-write package-lock.json and you may get the wrong versions of software pulled.

**Comment by Solexplorer** [comment]
I will remove the repo and start everything from the beginning, maybe it will solve the issue

**Comment by Solexplorer** [comment]
Can confirm using `npm ci` rather than `npm install` works.
Thanks @Westlad , the issue is now solved
