### ISSUE TITLE
Error: panicked at 'couldn't open /home/zokrates/code/gm17/ft-mint/out

### ISSUE THREAD

**Issue by adamdossa** [EYBlockchain/nightfall#18]
When trying to mint an opscoin, I get the below stack trace:
```
ganache_1           | personal_unlockAccount
zkp_1               |         
zkp_1               |         IN MINT...
zkp_1               |           Finding the relevant Shield and Verifier contracts
ganache_1           | eth_getBlockByNumber
ganache_1           | eth_getBlockByNumber
ganache_1           | eth_getBlockByNumber
zkp_1               |           FTokenShield contract address: 0x2cd4946Fb86584966A811EE387fFdDfC404236f9
zkp_1               |           Verifier contract address: 0x1A8555EFe8FaA218da938b69bFd3Fb4334bf9411
zkp_1               |           VerifierRegistry contract address: 0xdF92f5b4d45D8fB20213e649bb95176328962686
zkp_1               |           Reading vkIds from json file...
zkp_1               |           Existing Proof Variables:
zkp_1               |             A:  0x00000000000000000000000000000005 :  [ '5' ]
zkp_1               |             pkA:  0x0280a0d199e639cd82b91d862c225e1b6a6496646ceeb794f87304  :  [ '3025281131444327764113693',
zkp_1               |               '178345709554812776295359422658292249348' ]
zkp_1               |             S_A:  0x4E5584DC572CAA68E644A93F7C5B31E11FB3017F653F7530F7A5B9  :  [ '94700065928410846865015977',
zkp_1               |               '84387058196034363361276432521729910201' ]
zkp_1               |           New Proof Variables:
zkp_1               |             zA:  0xbfde36c2f51b3f0d28e04af61e1acc32332156d033f3c6a7571c71  :  [ '231954207077935784191909962',
zkp_1               |               '327146399389576260563932470810041064561' ]
zkp_1               |           inputs:
zkp_1               |           [ '5',
zkp_1               |             '231954207077935784191909962',
zkp_1               |             '327146399389576260563932470810041064561' ]
zkp_1               |           /app
zkp_1               |           gm17/ft-mint/
zkp_1               |           Computing proof with w=[pkA,S_A] x=[A,Z,1]
zkp_1               |             
zkp_1               |             Compute-witness: Executing the program C(w,x) with:
zkp_1               |              (w,x)= [ '5',
zkp_1               |               '3025281131444327764113693',
zkp_1               |               '178345709554812776295359422658292249348',
zkp_1               |               '94700065928410846865015977',
zkp_1               |               '84387058196034363361276432521729910201',
zkp_1               |               '231954207077935784191909962',
zkp_1               |               '327146399389576260563932470810041064561' ] ...
zkp_1               |             a  5 3025281131444327764113693 178345709554812776295359422658292249348 94700065928410846865015977 84387058196034363361276432521729910201 231954207077935784191909962 327146399389576260563932470810041064561
api-gateway_1       | error: POST:/coin/mint
api-gateway_1       | 		{}
api-gateway_1       | 		{"body":{"A":"0x00000000000000000000000000000005","pk_A":"0x0280a0d199e639cd82b91d862c225e1b6a6496646ceeb794f87304","S_A":"0x4E5584DC572CAA68E644A93F7C5B31E11FB3017F653F7530F7A5B9"}}
zkp_1               |             Error: panicked at 'couldn't open /home/zokrates/code/gm17/ft-mint/out: No such file or directory (os error 2)', zokrates_cli/src/bin.rs:309:29
zkp_1               |             note: Run with `RUST_BACKTRACE=1` for a backtrace.
zkp_1               |             
zkp_1               |                 at IncomingMessage.stream.on (/app/src/zokrates.js:37:16)
zkp_1               |                 at IncomingMessage.emit (events.js:198:15)
zkp_1               |                 at endReadableNT (_stream_readable.js:1139:12)
zkp_1               |                 at processTicksAndRejections (internal/process/task_queues.js:81:17)
api-gateway_1       | 		{"params":{}}
api-gateway_1       | 		{"query":{}}
api-gateway_1       | 	
```

If I do:
```
docker exec -ti 215862c9b80e32e42fb2cb88692eef21670eebfbce50507bc8797bfa5b8c7c74 bash
```
and look for the directory in the error I get:
```
zokrates@215862c9b80e:~/code$ cd /home/zokrates/code
zokrates@215862c9b80e:~/code$ ls -ltr
total 0
```

Any ideas appreciated ;-). Thanks!

**Comment by adamdossa** [comment]
I do seem to have the files locally:
```
/Development/Ethereum/nightfall-master/zkp/code/gm17/nft-transfer
nft-transfer$ ls -ltr
total 2906976
-rwxr-xr-x@ 1 adam  staff        5773 31 May 13:30 nft-transfer.pcode
-rw-r--r--  1 adam  staff      775876 31 May 20:34 nft-transfer.code
-rw-r--r--  1 adam  staff   193849817 31 May 20:43 out
-rw-r--r--  1 adam  staff   214248742 31 May 20:43 out.code
-rw-r--r--  1 adam  staff  1056866122 31 May 20:43 proving.key
-rw-r--r--  1 adam  staff        2380 31 May 20:43 verification.key
-rw-r--r--  1 adam  staff     8708476 31 May 20:43 variables.inf
-rw-r--r--  1 adam  staff       24424 31 May 20:43 verifier.sol
-rw-r--r--  1 adam  staff        2335 31 May 20:43 nft-transfer-vk.json
```

**Comment by iAmMichaelConnor** [comment]
It could be that you’ve renamed the repo folder’s name from ‘nightfall’ to ‘nightfall-master’. I think the docker image names currently inherit their names from the local  filing structure. And the code expects ‘nightfall’ to be the name.
Try changing the folder back to ‘nightfall’. Then kill the running docker containers (‘docker stop $(docker ps -aq)’ then ‘docker rm $(docker ps -aq)’ )
Then ‘docker-proxy start’. Then ‘docker-compose build’. Then ‘./zkp-demo’ to restart things.

Apologies for formatting; I’m on mobile.

**Comment by adamdossa** [comment]
That worked - thanks for your help!

**Comment by walter-grace** [comment]
I tried this example above because I am getting similar error; I am still struggling. Any suggestions?
I just keep seeing the please wait page. Cheers,


_zkp_1               |   { [Error: ENOENT: no such file or directory, open './src/vkIds.json']
zkp_1               |     errno: -2,
zkp_1               |     code: 'ENOENT',
zkp_1               |     syscall: 'open',
zkp_1               |     path: './src/vkIds.json' }
api-gateway_1       | error: POST:/coin/mint
api-gateway_1       | 		{}
api-gateway_1       | 		{"body":{"A":"0x0000000000000000000000000000000a","pk_A":"0xc53fcbf59524b84391839971e48473e48c0079034fb8cbd6ec1525","S_A":"0x5A20B022623E590F26F91832677D3AD7C1944F74ED2C6065EC62BC"}}
api-gateway_1       | 		{"params":{}}
api-gateway_1       | 		{"query":{}}_

**Comment by walter-grace** [comment]
closing: bigger issue is to make sure node@10 is involved and install; 
personally i used npm install vs. npm ci; just worked for me
