### ISSUE TITLE
Error when exporting verifier `ft-transfer`

### ISSUE THREAD

**Issue by CruzMolina** [EYBlockchain/nightfall#25]
Currently when trying to run `npm run setup-all`, I seem to consistently hit the following error during `ft-transfer` setup:

```
Export Verifier ft-transfer ...
  Error: panicked at '�couldn't open verification.key: No such file or directory (os error 2)', zokrates_cli/src/bin.rs:477:33
  note: Run with `RUST_BACKTRACE=1` for a backtrace.
  
      at IncomingMessage.stream.on (/Users/cruzmolina/Code/nightfall/zkp/src/zokrates.js:37:16)
      at IncomingMessage.emit (events.js:194:15)
      at endReadableNT (_stream_readable.js:1107:12)
      at process.internalTickCallback (internal/process/next_tick.js:72:19)
  undefined
  ft-transfer SETUP MESSAGE: EXPORT-VERIFIER COMPLETE
�cp: cannot stat '/home/zokrates/proving.key': No such file or directory
cp: cannot stat '/home/zokrates/verification.key': No such file or directory
Icp: cannot stat '/home/zokrates/verifier.sol': No such file or directory
```

this then triggers the key extraction error for `ft-transfer`.

Will try to up docker memory resources and see if that resolves the issue. 🤞 

OS: macOS High Sierra 10.13.6

**Comment by CruzMolina** [comment]
Resolved by increasing docker memory resources 👍
