### ISSUE TITLE
Couldn't open witness: No such file

### ISSUE THREAD

**Issue by DoubleCherish** [EYBlockchain/nightfall#307]
when i run ./nightfall 
then click mint EY OpsCoin Commitment
then occur some error
```
Compute-witness...
zkp_1               |     ./zokrates compute-witness -a 27997765721359981299583558596036042657472381437987280457519511607987563779 3 215774222513396048137754574542153298021 335996578179477273760758828443404809147 315890920702477750438418171842903433840 337837609597197084938823680958343100123 97252919044859706891731934701559606308 117573481856989263212980807793649040178 -i code/gm17/ft-mint/out
zkp_1               |     (you can paste the above line into the container to debug the 'compute-witness' step)
zkp_1               |     
zkp_1               |     Generating Proof := P(pk,w,x)
zkp_1               |     Backend being used gm17
zkp_1               |     POST:/mintFTCommitment
zkp_1               |         {"error":"panicked at 'couldn't open witness: No such file or directory (os error 2)', zokrates_cli/src/bin.rs:464:29\nnote: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.\n"}
zkp_1               |         {
zkp_1               |      "errorStack": [
zkp_1               |       "Error: panicked at 'couldn't open witness: No such file or directory (os error 2)', zokrates_cli/src/bin.rs:464:29",
zkp_1               |       "note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.",
zkp_1               |       "",
zkp_1               |       "    at IncomingMessage.stream.on (/app/src/zokrates.js:35:16)",
zkp_1               |       "    at IncomingMessage.emit (events.js:198:15)",
zkp_1               |       "    at endReadableNT (_stream_readable.js:1139:12)",
zkp_1               |       "    at processTicksAndRejections (internal/process/task_queues.js:81:17)"
zkp_1               |      ]
zkp_1               |     }
zkp_1               |         {"body":{"amount":"0x00000000000000000000000000000003","ownerPublicKey":"0xa2549a87eca83ce518c3463c1c1db065fcc6964d056d4377ad12a0e5f51b33bb"}}
zkp_1               |         {"params":{}}
zkp_1               |         {"query":{}}
zkp_1               |       
zkp_1               |     {}
zkp_1               |     [object Object]

```

**Comment by iAmMichaelConnor** [comment]
@DoubleCherish thanks for raising an issue!

It looks like it can't find the 'witness' file(s) which are required to generate proofs.

Did you run the crucial Installation step (from the README): `npm run setupAll`? This script takes a long time to run (around an hour), and it generates the missing files for you.
(_please note: the command `npm run setupAll` is about to be replaced with `./nightfall-generate-trusted-setup` in PR #297 - so be sure to keep an eye on the latest README over the next week_)

**Comment by iAmMichaelConnor** [comment]
@DoubleCherish you can check inside `./zkp/code/gm17/ft-mint/` to see if there is a file called `witness` (amongst several other files). If there is only a file called `ft-mint.code`, this means the above `npm run setupAll` script hasn't been run.

**Comment by DoubleCherish** [comment]
@iAmMichaelConnor inside` ./zkp/code/gm17/ft-mint/` , there are` ft-mint.code ft-mint-vk.json out out.code proving.key verifier.sol etc` but there no file called` witness`

**Comment by Westlad** [comment]
closing as this thread is being dealt with in #308.
