### ISSUE TITLE
Truffle box not working. Suspect issue with images moving

### ISSUE THREAD

**Issue by Genysys** [EYBlockchain/nightfall#333]
# Description

I am trying to run this via a truffle box but unsuccessful so far. it fails at `npm run setup` 

#### System information

OS: MacOS Mojave
Truffle v5.0.19 (core: 5.0.19)
Solidity v0.5.0 (solc-js)
Node v10.15.3
Web3.js v1.0.0-beta.37
Docker version 19.03.1, build 74b1e89

#### Expected behaviour

`npm run setup`

Result: Trusted set up run

#### Actual behaviour

`npm run setup`

```
Filing checks for codeFile: nft-transfer.pcode
/Users/samueldare/Documents/Code/Ethereum/nightfall/code/gm17/nft-transfer/nft-transfer.pcode was copied to safe-dump/nft-transfer.pcode
Checking for 'import' files in the .code file nft-transfer
codeFileName: nft-transfer
codeFile: nft-transfer.code
outputDirPath: /Users/samueldare/Documents/Code/Ethereum/nightfall/code/gm17/nft-transfer/
backend: gm17
a: null
ZoKrates running with Nodejs environment setup
Running the container; mounted: /Users/samueldare/Documents/Code/Ethereum/nightfall/code/gm17/nft-transfer/:/home/zokrates/code/:cached
{ Error: (HTTP code 404) no such image - No such image: michaelconnor/zok:2Jan2019 
    at /Users/samueldare/Documents/Code/Ethereum/nightfall/node_modules/docker-modem/lib/modem.js:239:17
    at getCause (/Users/samueldare/Documents/Code/Ethereum/nightfall/node_modules/docker-modem/lib/modem.js:269:7)
    at Modem.buildPayload (/Users/samueldare/Documents/Code/Ethereum/nightfall/node_modules/docker-modem/lib/modem.js:238:5)
    at IncomingMessage.<anonymous> (/Users/samueldare/Documents/Code/Ethereum/nightfall/node_modules/docker-modem/lib/modem.js:214:14)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  reason: 'no such image',
  statusCode: 404,
  json: { message: 'No such image: michaelconnor/zok:2Jan2019' } }

Container running for nft-transfer
TypeError: Cannot read property 'id' of undefined
    at id (/Users/samueldare/Documents/Code/Ethereum/nightfall/code/index.js:140:68)
    at process._tickCallback (internal/process/next_tick.js:68:7)

****************************************************************************************************************** 
Trusted setup has failed for nft-transfer.code. Please see above for additional information relating to this error. 
The most common cause of errors when using this tool is insufficient allocation of resources to Docker. 
You can go to Docker's settings and increase the RAM being allocated to Docker. See the README for more details. 
******************************************************************************************************************

```

I think it might have to do with the docker files being moved.

#### Steps to reproduce the behaviour

- `truffle unbox nightfall`
- `npm run setup`

#### Backtrace

````
[backtrace]
````
s
#### Logs

s
````
[logs]
````s

**Comment by ChaitanyaKonda** [comment]
Closing because this issue needs to be raised with truffle.
