### ISSUE TITLE
Trusted setup has failed

### ISSUE THREAD

**Issue by SinTan1071** [EYBlockchain/nightfall#36]
```npm run setup-all```failed, I am sure my docker is already set memory to 8GB with 4GB of swap space, here are some logs:

```
Be warned, this could take up to an hour!
? Continue? y
Checking pwd...
  pwd: /www/code/blockchain/EYBlockChain/nightfall/zkp
  pwdName: zkp


dirs in /www/code/blockchain/EYBlockChain/nightfall/zkp/code/ :
[ '/www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17',
  '/www/code/blockchain/EYBlockChain/nightfall/zkp/code/safe-dump' ]


relevant dirs in /www/code/blockchain/EYBlockChain/nightfall/zkp/code/ :
[ '/www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17' ]


dirs in /www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17 :
[ '/www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/ft-burn',
  '/www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/ft-mint',
  '/www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/ft-transfer',
  '/www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/nft-burn',
  '/www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/nft-mint',
  '/www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/nft-transfer' ]


Found existing files: [ 'ft-burn.code', 'ft-burn.pcode' ] in /www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/ft-burn


If you continue, these files will be deleted (except for the '.pcode' file and any '.code' dependencies).
? Continue with the trusted setup? y/n  y

Files remaining: [ 'ft-burn.code', 'ft-burn.pcode' ] in /www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/ft-burn

Filing checks for codeFile: ft-burn.pcode
/www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/ft-burn/ft-burn.pcode was copied to safe-dump/ft-burn.pcode
Checking for 'import' files in the .code file ft-burn
codeFileName: ft-burn
codeFile: ft-burn.code
outputDirPath: /www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/ft-burn/
backend: gm17
a: null
ZoKrates running with Nodejs environment setup
Running the container; mounted: /www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/ft-burn/:/home/zokrates/code/:cached

Container running for ft-burn
Container id for ft-burn : cbc6e3c7ee7d7d478e033452d745e2c70f9cf9414b0e24fd47439153f73dcbfb
To connect to the ft-burn  container manually: 'docker exec -ti cbc6e3c7ee7d7d478e033452d745e2c70f9cf9414b0e24fd47439153f73dcbfb bash'

Compile ft-burn ...
  Compiling code in the container - this can take some minutes...
  +Compiling /home/zokrates/code/ft-burn.code

  ft-burn SETUP MESSAGE: COMPILATION COMPLETE

Setup ft-burn ...
  Setup: computing (pk,vk) := G(C,toxic) - this can take many minutes...
  Error: panicked at 'couldn't open out: No such file or directory (os error 2)', zokrates_cli/src/bin.rs:408:29
  note: Run with `RUST_BACKTRACE=1` for a backtrace.

      at IncomingMessage.stream.on (/www/code/blockchain/EYBlockChain/nightfall/zkp/src/zokrates.js:37:16)
      at IncomingMessage.emit (events.js:194:15)
      at endReadableNT (_stream_readable.js:1125:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
  undefined
  SETUP MESSAGE: SETUP COMPLETE

Export Verifier ft-burn ...
  Error: panicked at 'couldn't open verification.key: No such file or directory (os error 2)', zokrates_cli/src/bin.rs:477:33
  note: Run with `RUST_BACKTRACE=1` for a backtrace.
  Exporting verifier...

      at IncomingMessage.stream.on (/www/code/blockchain/EYBlockChain/nightfall/zkp/src/zokrates.js:37:16)
      at IncomingMessage.emit (events.js:194:15)
      at endReadableNT (_stream_readable.js:1125:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
  undefined
  ft-burn SETUP MESSAGE: EXPORT-VERIFIER COMPLETE
�cp: cannot stat '/home/zokrates/out': No such file or directory
cp: cannot stat '/home/zokrates/out.code': No such file or directory
cp: cannot stat '/home/zokrates/proving.key': No such file or directory
cp: cannot stat '/home/zokrates/verification.key': No such file or directory
cp: cannot stat '/home/zokrates/variables.inf': No such file or directory
cp: cannot stat '/home/zokrates/verifier.sol': No such file or directory

ft-burn SETUP MESSAGE: FILES COPIED TO THE MOUNTED DIR WITHIN THE CONTAINER. THE FILES WILL NOW ALSO EXIST WITHIN YOUR LOCALHOST'S FOLDER: /www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/ft-burn/

Key extraction ft-burn ...
  { Error: ENOENT: no such file or directory, open '/www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/ft-burn/verifier.sol'
      at Object.openSync (fs.js:438:3)
      at Object.readFileSync (fs.js:343:35)
      at Object.readFileSync (/www/code/blockchain/EYBlockChain/nightfall/zkp/code/tools-key-extractor.js:18:6)
      at keyExtractor (/www/code/blockchain/EYBlockChain/nightfall/zkp/code/index.js:249:41)
      at process._tickCallback (internal/process/next_tick.js:68:7)
    errno: -2,
    syscall: 'open',
    code: 'ENOENT',
    path:
     '/www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/ft-burn/verifier.sol' }

  ******************************************************************************************************************
  Trusted setup has failed for ft-burn.code. Please see above for additional information relating to this error.
  The most common cause of errors when using this tool is insufficient allocation of resources to Docker.
  You can go to Docker's settings and increase the RAM being allocated to Docker. See the README for more details.
  ******************************************************************************************************************


  Found existing files: [ 'ft-mint.code', 'ft-mint.pcode' ] in /www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/ft-mint


  If you continue, these files will be deleted (except for the '.pcode' file and any '.code' dependencies).
? Continue with the trusted setup? y/n  y

  Files remaining: [ 'ft-mint.code', 'ft-mint.pcode' ] in /www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/ft-mint

  Filing checks for codeFile: ft-mint.pcode
  /www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/ft-mint/ft-mint.pcode was copied to safe-dump/ft-mint.pcode
  Checking for 'import' files in the .code file ft-mint
codeFileName: ft-mint
codeFile: ft-mint.code
outputDirPath: /www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/ft-mint/
backend: gm17
a: null
ZoKrates running with Nodejs environment setup
Running the container; mounted: /www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/ft-mint/:/home/zokrates/code/:cached

Container running for ft-mint
Container id for ft-mint : f90d67c4488585ec28a8fa77a573dda14816cf34c56d8570f80431d8f071107a
To connect to the ft-mint  container manually: 'docker exec -ti f90d67c4488585ec28a8fa77a573dda14816cf34c56d8570f80431d8f071107a bash'

Compile ft-mint ...
  Compiling code in the container - this can take some minutes...
  +Compiling /home/zokrates/code/ft-mint.code

  ft-mint SETUP MESSAGE: COMPILATION COMPLETE

Setup ft-mint ...
  Setup: computing (pk,vk) := G(C,toxic) - this can take many minutes...
  Error: panicked at 'couldn't open out: No such file or directory (os error 2)', zokrates_cli/src/bin.rs:408:29
  note: Run with `RUST_BACKTRACE=1` for a backtrace.

      at IncomingMessage.stream.on (/www/code/blockchain/EYBlockChain/nightfall/zkp/src/zokrates.js:37:16)
      at IncomingMessage.emit (events.js:194:15)
      at endReadableNT (_stream_readable.js:1125:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
  undefined
  SETUP MESSAGE: SETUP COMPLETE

Export Verifier ft-mint ...
  Error: panicked at 'couldn't open verification.key: No such file or directory (os error 2)', zokrates_cli/src/bin.rs:477:33
  note: Run with `RUST_BACKTRACE=1` for a backtrace.
  Exporting verifier...

      at IncomingMessage.stream.on (/www/code/blockchain/EYBlockChain/nightfall/zkp/src/zokrates.js:37:16)
      at IncomingMessage.emit (events.js:194:15)
      at endReadableNT (_stream_readable.js:1125:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
  undefined
  ft-mint SETUP MESSAGE: EXPORT-VERIFIER COMPLETE
�cp: cannot stat '/home/zokrates/out': No such file or directory
cp: cannot stat '/home/zokrates/out.code': No such file or directory
'cp: cannot stat '/home/zokrates/proving.key': No such file or directory
cp: cannot stat '/home/zokrates/verification.key': No such file or directory
cp: cannot stat '/home/zokrates/variables.inf': No such file or directory
cp: cannot stat '/home/zokrates/verifier.sol': No such file or directory

ft-mint SETUP MESSAGE: FILES COPIED TO THE MOUNTED DIR WITHIN THE CONTAINER. THE FILES WILL NOW ALSO EXIST WITHIN YOUR LOCALHOST'S FOLDER: /www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/ft-mint/

Key extraction ft-mint ...
  { Error: ENOENT: no such file or directory, open '/www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/ft-mint/verifier.sol'
      at Object.openSync (fs.js:438:3)
      at Object.readFileSync (fs.js:343:35)
      at Object.readFileSync (/www/code/blockchain/EYBlockChain/nightfall/zkp/code/tools-key-extractor.js:18:6)
      at keyExtractor (/www/code/blockchain/EYBlockChain/nightfall/zkp/code/index.js:249:41)
      at process._tickCallback (internal/process/next_tick.js:68:7)
    errno: -2,
    syscall: 'open',
    code: 'ENOENT',
    path:
     '/www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/ft-mint/verifier.sol' }

  ******************************************************************************************************************
  Trusted setup has failed for ft-mint.code. Please see above for additional information relating to this error.
  The most common cause of errors when using this tool is insufficient allocation of resources to Docker.
  You can go to Docker's settings and increase the RAM being allocated to Docker. See the README for more details.
  ******************************************************************************************************************


  Found existing files: [ 'aux-adder.code',
    'aux-adder.pcode',
    'ft-transfer.code',
    'ft-transfer.pcode' ] in /www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/ft-transfer


  If you continue, these files will be deleted (except for the '.pcode' file and any '.code' dependencies).
? Continue with the trusted setup? y/n  y
  deleting ft-transfer.code

  Files remaining: [ 'aux-adder.code',
    'aux-adder.pcode',
    'ft-transfer.code',
    'ft-transfer.pcode' ] in /www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/ft-transfer

  Filing checks for codeFile: ft-transfer.pcode
  /www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/ft-transfer/ft-transfer.pcode was copied to safe-dump/ft-transfer.pcode
  Checking for 'import' files in the .code file ft-transfer
codeFileName: ft-transfer
codeFile: ft-transfer.code
outputDirPath: /www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/ft-transfer/
backend: gm17
a: null
ZoKrates running with Nodejs environment setup
Running the container; mounted: /www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/ft-transfer/:/home/zokrates/code/:cached

Container running for ft-transfer
Container id for ft-transfer : e71b3ec3aaae022e80339640c8183d41044dc852b0b52a7651b2534b5604b91a
To connect to the ft-transfer  container manually: 'docker exec -ti e71b3ec3aaae022e80339640c8183d41044dc852b0b52a7651b2534b5604b91a bash'

Compile ft-transfer ...
  Compiling code in the container - this can take some minutes...
  /Compiling /home/zokrates/code/ft-transfer.code

  ft-transfer SETUP MESSAGE: COMPILATION COMPLETE

Setup ft-transfer ...
  Setup: computing (pk,vk) := G(C,toxic) - this can take many minutes...
  Error: panicked at 'couldn't open out: No such file or directory (os error 2)', zokrates_cli/src/bin.rs:408:29
  note: Run with `RUST_BACKTRACE=1` for a backtrace.

      at IncomingMessage.stream.on (/www/code/blockchain/EYBlockChain/nightfall/zkp/src/zokrates.js:37:16)
      at IncomingMessage.emit (events.js:194:15)
      at endReadableNT (_stream_readable.js:1125:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
  undefined
  SETUP MESSAGE: SETUP COMPLETE

Export Verifier ft-transfer ...
  Error: panicked at 'Fcouldn't open verification.key: No such file or directory (os error 2)', zokrates_cli/src/bin.rs::477:33
  note: Run with `RUST_BACKTRACE=1` for a backtrace.

      at IncomingMessage.stream.on (/www/code/blockchain/EYBlockChain/nightfall/zkp/src/zokrates.js:37:16)
      at IncomingMessage.emit (events.js:194:15)
      at endReadableNT (_stream_readable.js:1125:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
  undefined
  ft-transfer SETUP MESSAGE: EXPORT-VERIFIER COMPLETE
�cp: cannot stat '/home/zokrates/out': No such file or directory
cp: cannot stat '/home/zokrates/out.code': No such file or directory
cp: cannot stat '/home/zokrates/proving.key': No such file or directory
cp: cannot stat '/home/zokrates/verification.key': No such file or directory
cp: cannot stat '/home/zokrates/variables.inf': No such file or directory
cp: cannot stat '/home/zokrates/verifier.sol': No such file or directory

ft-transfer SETUP MESSAGE: FILES COPIED TO THE MOUNTED DIR WITHIN THE CONTAINER. THE FILES WILL NOW ALSO EXIST WITHIN YOUR LOCALHOST'S FOLDER: /www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/ft-transfer/

Key extraction ft-transfer ...
  { Error: ENOENT: no such file or directory, open '/www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/ft-transfer/verifier.sol'
      at Object.openSync (fs.js:438:3)
      at Object.readFileSync (fs.js:343:35)
      at Object.readFileSync (/www/code/blockchain/EYBlockChain/nightfall/zkp/code/tools-key-extractor.js:18:6)
      at keyExtractor (/www/code/blockchain/EYBlockChain/nightfall/zkp/code/index.js:249:41)
      at process._tickCallback (internal/process/next_tick.js:68:7)
    errno: -2,
    syscall: 'open',
    code: 'ENOENT',
    path:
     '/www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/ft-transfer/verifier.sol' }

  ******************************************************************************************************************
  Trusted setup has failed for ft-transfer.code. Please see above for additional information relating to this error.
  The most common cause of errors when using this tool is insufficient allocation of resources to Docker.
  You can go to Docker's settings and increase the RAM being allocated to Docker. See the README for more details.
  ******************************************************************************************************************


  Found existing files: [ 'nft-burn.code', 'nft-burn.pcode' ] in /www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/nft-burn


  If you continue, these files will be deleted (except for the '.pcode' file and any '.code' dependencies).
? Continue with the trusted setup? y/n  y

  Files remaining: [ 'nft-burn.code', 'nft-burn.pcode' ] in /www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/nft-burn

  Filing checks for codeFile: nft-burn.pcode
  /www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/nft-burn/nft-burn.pcode was copied to safe-dump/nft-burn.pcode
  Checking for 'import' files in the .code file nft-burn
codeFileName: nft-burn
codeFile: nft-burn.code
outputDirPath: /www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/nft-burn/
backend: gm17
a: null
ZoKrates running with Nodejs environment setup
Running the container; mounted: /www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/nft-burn/:/home/zokrates/code/:cached

Container running for nft-burn
Container id for nft-burn : 598336c6f3cb18c351a4466d40fd2d313c72b24d90d4c0ab8ceff0c36ad3fb82
To connect to the nft-burn  container manually: 'docker exec -ti 598336c6f3cb18c351a4466d40fd2d313c72b24d90d4c0ab8ceff0c36ad3fb82 bash'

Compile nft-burn ...
  Compiling code in the container - this can take some minutes...
  ,Compiling /home/zokrates/code/nft-burn.code

  nft-burn SETUP MESSAGE: COMPILATION COMPLETE

Setup nft-burn ...
  Setup: computing (pk,vk) := G(C,toxic) - this can take many minutes...
  Error: panicked at 'couldn't open out: No such file or directory (os error 2)', zokrates_cli/src/bin.rs:408:29
  note: Run with `RUST_BACKTRACE=1` for a backtrace.

      at IncomingMessage.stream.on (/www/code/blockchain/EYBlockChain/nightfall/zkp/src/zokrates.js:37:16)
      at IncomingMessage.emit (events.js:194:15)
      at endReadableNT (_stream_readable.js:1125:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
  undefined
  SETUP MESSAGE: SETUP COMPLETE

Export Verifier nft-burn ...
  Error: panicked at 'couldn't open verification.key: No such file or directory (os error 2)', zokrates_cli/src/bin.rs:477:33
  note: Run with `RUST_BACKTRACE=1` for a backtrace.

      at IncomingMessage.stream.on (/www/code/blockchain/EYBlockChain/nightfall/zkp/src/zokrates.js:37:16)
      at IncomingMessage.emit (events.js:194:15)
      at endReadableNT (_stream_readable.js:1125:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
  undefined
  nft-burn SETUP MESSAGE: EXPORT-VERIFIER COMPLETE
�cp: cannot stat '/home/zokrates/out': No such file or directory
cp: cannot stat '/home/zokrates/out.code': No such file or directory
cp: cannot stat '/home/zokrates/proving.key': No such file or directory
cp: cannot stat '/home/zokrates/verification.key': No such file or directory
cp: cannot stat '/home/zokrates/variables.inf': No such file or directory
cp: cannot stat '/home/zokrates/verifier.sol': No such file or directory

nft-burn SETUP MESSAGE: FILES COPIED TO THE MOUNTED DIR WITHIN THE CONTAINER. THE FILES WILL NOW ALSO EXIST WITHIN YOUR LOCALHOST'S FOLDER: /www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/nft-burn/

Key extraction nft-burn ...
  { Error: ENOENT: no such file or directory, open '/www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/nft-burn/verifier.sol'
      at Object.openSync (fs.js:438:3)
      at Object.readFileSync (fs.js:343:35)
      at Object.readFileSync (/www/code/blockchain/EYBlockChain/nightfall/zkp/code/tools-key-extractor.js:18:6)
      at keyExtractor (/www/code/blockchain/EYBlockChain/nightfall/zkp/code/index.js:249:41)
      at process._tickCallback (internal/process/next_tick.js:68:7)
    errno: -2,
    syscall: 'open',
    code: 'ENOENT',
    path:
     '/www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/nft-burn/verifier.sol' }

  ******************************************************************************************************************
  Trusted setup has failed for nft-burn.code. Please see above for additional information relating to this error.
  The most common cause of errors when using this tool is insufficient allocation of resources to Docker.
  You can go to Docker's settings and increase the RAM being allocated to Docker. See the README for more details.
  ******************************************************************************************************************


  Found existing files: [ 'nft-mint.code', 'nft-mint.pcode' ] in /www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/nft-mint


  If you continue, these files will be deleted (except for the '.pcode' file and any '.code' dependencies).
? Continue with the trusted setup? y/n  y

  Files remaining: [ 'nft-mint.code', 'nft-mint.pcode' ] in /www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/nft-mint

  Filing checks for codeFile: nft-mint.pcode
  /www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/nft-mint/nft-mint.pcode was copied to safe-dump/nft-mint.pcode
  Checking for 'import' files in the .code file nft-mint
codeFileName: nft-mint
codeFile: nft-mint.code
outputDirPath: /www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/nft-mint/
backend: gm17
a: null
ZoKrates running with Nodejs environment setup
Running the container; mounted: /www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/nft-mint/:/home/zokrates/code/:cached

Container running for nft-mint
Container id for nft-mint : 3cb47d37cfecb412b468634411484703a2d067b05c1eff21b36c98cd0a8ea498
To connect to the nft-mint  container manually: 'docker exec -ti 3cb47d37cfecb412b468634411484703a2d067b05c1eff21b36c98cd0a8ea498 bash'

Compile nft-mint ...
  Compiling code in the container - this can take some minutes...
  ,Compiling /home/zokrates/code/nft-mint.code

  nft-mint SETUP MESSAGE: COMPILATION COMPLETE

Setup nft-mint ...
  Setup: computing (pk,vk) := G(C,toxic) - this can take many minutes...
  Error: panicked at 'couldn't open out: No such file or directory (os error 2)', zokrates_cli/src/bin.rs:408:29
  note: Run with `RUST_BACKTRACE=1` for a backtrace.

      at IncomingMessage.stream.on (/www/code/blockchain/EYBlockChain/nightfall/zkp/src/zokrates.js:37:16)
      at IncomingMessage.emit (events.js:194:15)
      at endReadableNT (_stream_readable.js:1125:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
  undefined
  SETUP MESSAGE: SETUP COMPLETE

Export Verifier nft-mint ...
  Error: panicked at 'couldn't open verification.key: No such file or directory (os error 2)', zokrates_cli/src/bin.rs:477:33
  note: Run with `RUST_BACKTRACE=1` for a backtrace.
  Exporting verifier...

      at IncomingMessage.stream.on (/www/code/blockchain/EYBlockChain/nightfall/zkp/src/zokrates.js:37:16)
      at IncomingMessage.emit (events.js:194:15)
      at endReadableNT (_stream_readable.js:1125:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
  undefined
  nft-mint SETUP MESSAGE: EXPORT-VERIFIER COMPLETE
@cp: cannot stat '/home/zokrates/out': No such file or directory
�cp: cannot stat '/home/zokrates/out.code': No such file or directory
cp: cannot stat '/home/zokrates/proving.key': No such file or directory
�cp: cannot stat '/home/zokrates/verification.key': No such file or directory
cp: cannot stat '/home/zokrates/variables.inf': No such file or directory
cp: cannot stat '/home/zokrates/verifier.sol': No such file or directory

nft-mint SETUP MESSAGE: FILES COPIED TO THE MOUNTED DIR WITHIN THE CONTAINER. THE FILES WILL NOW ALSO EXIST WITHIN YOUR LOCALHOST'S FOLDER: /www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/nft-mint/

Key extraction nft-mint ...
  { Error: ENOENT: no such file or directory, open '/www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/nft-mint/verifier.sol'
      at Object.openSync (fs.js:438:3)
      at Object.readFileSync (fs.js:343:35)
      at Object.readFileSync (/www/code/blockchain/EYBlockChain/nightfall/zkp/code/tools-key-extractor.js:18:6)
      at keyExtractor (/www/code/blockchain/EYBlockChain/nightfall/zkp/code/index.js:249:41)
      at process._tickCallback (internal/process/next_tick.js:68:7)
    errno: -2,
    syscall: 'open',
    code: 'ENOENT',
    path:
     '/www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/nft-mint/verifier.sol' }

  ******************************************************************************************************************
  Trusted setup has failed for nft-mint.code. Please see above for additional information relating to this error.
  The most common cause of errors when using this tool is insufficient allocation of resources to Docker.
  You can go to Docker's settings and increase the RAM being allocated to Docker. See the README for more details.
  ******************************************************************************************************************


  Found existing files: [ 'nft-transfer.code', 'nft-transfer.pcode' ] in /www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/nft-transfer


  If you continue, these files will be deleted (except for the '.pcode' file and any '.code' dependencies).
? Continue with the trusted setup? y/n  y

  Files remaining: [ 'nft-transfer.code', 'nft-transfer.pcode' ] in /www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/nft-transfer

  Filing checks for codeFile: nft-transfer.pcode
  /www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/nft-transfer/nft-transfer.pcode was copied to safe-dump/nft-transfer.pcode
  Checking for 'import' files in the .code file nft-transfer
codeFileName: nft-transfer
codeFile: nft-transfer.code
outputDirPath: /www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/nft-transfer/
backend: gm17
a: null
ZoKrates running with Nodejs environment setup
Running the container; mounted: /www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/nft-transfer/:/home/zokrates/code/:cached

Container running for nft-transfer
Container id for nft-transfer : 75976dab145a11b08f845986595e4ba6afb9ed4975a6ec8b9d8599c6d887c350
To connect to the nft-transfer  container manually: 'docker exec -ti 75976dab145a11b08f845986595e4ba6afb9ed4975a6ec8b9d8599c6d887c350 bash'

Compile nft-transfer ...
  Compiling code in the container - this can take some minutes...
  0Compiling /home/zokrates/code/nft-transfer.code

  nft-transfer SETUP MESSAGE: COMPILATION COMPLETE

Setup nft-transfer ...
  Setup: computing (pk,vk) := G(C,toxic) - this can take many minutes...
  Error: panicked at 'couldn't open out: No such file or directory (os error 2)', zokrates_cli/src/bin.rs:408:29
  note: Run with `RUST_BACKTRACE=1` for a backtrace.
  Performing setup...

      at IncomingMessage.stream.on (/www/code/blockchain/EYBlockChain/nightfall/zkp/src/zokrates.js:37:16)
      at IncomingMessage.emit (events.js:194:15)
      at endReadableNT (_stream_readable.js:1125:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
  undefined
  SETUP MESSAGE: SETUP COMPLETE

Export Verifier nft-transfer ...
  Error: panicked at 'couldn't open verification.key: No such file or directory (os error 2)', zokrates_cli/src/bin.rs:477:33
  note: Run with `RUST_BACKTRACE=1` for a backtrace.

      at IncomingMessage.stream.on (/www/code/blockchain/EYBlockChain/nightfall/zkp/src/zokrates.js:37:16)
      at IncomingMessage.emit (events.js:194:15)
      at endReadableNT (_stream_readable.js:1125:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
  undefined
  nft-transfer SETUP MESSAGE: EXPORT-VERIFIER COMPLETE
�cp: cannot stat '/home/zokrates/out': No such file or directory
cp: cannot stat '/home/zokrates/out.code': No such file or directory
cp: cannot stat '/home/zokrates/proving.key': No such file or directory
cp: cannot stat '/home/zokrates/verification.key': No such file or directory
cp: cannot stat '/home/zokrates/variables.inf': No such file or directory
cp: cannot stat '/home/zokrates/verifier.sol': No such file or directory

nft-transfer SETUP MESSAGE: FILES COPIED TO THE MOUNTED DIR WITHIN THE CONTAINER. THE FILES WILL NOW ALSO EXIST WITHIN YOUR LOCALHOST'S FOLDER: /www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/nft-transfer/

Key extraction nft-transfer ...
  { Error: ENOENT: no such file or directory, open '/www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/nft-transfer/verifier.sol'
      at Object.openSync (fs.js:438:3)
      at Object.readFileSync (fs.js:343:35)
      at Object.readFileSync (/www/code/blockchain/EYBlockChain/nightfall/zkp/code/tools-key-extractor.js:18:6)
      at keyExtractor (/www/code/blockchain/EYBlockChain/nightfall/zkp/code/index.js:249:41)
      at process._tickCallback (internal/process/next_tick.js:68:7)
    errno: -2,
    syscall: 'open',
    code: 'ENOENT',
    path:
     '/www/code/blockchain/EYBlockChain/nightfall/zkp/code/gm17/nft-transfer/verifier.sol' }

  ******************************************************************************************************************
  Trusted setup has failed for nft-transfer.code. Please see above for additional information relating to this error.
  The most common cause of errors when using this tool is insufficient allocation of resources to Docker.
  You can go to Docker's settings and increase the RAM being allocated to Docker. See the README for more details.
  ******************************************************************************************************************
```

**Comment by iAmMichaelConnor** [comment]
It looks like it's fallen over whilst trying to do the `Compile ft-burn ...` step. You'd usually see a huge amount of information (pages and pages) being output to the console before the `Setup ft-burn ...` message.

Unfortunately, despite you mentioning that you're running Docker with 8gb ram and 4gb swap, this is probably an issue with Docker falling over due to insufficient resources.

If there's any more memory you can allocate to Docker (just for this trusted setup stage), I'd recommend doing so. Also maybe 'kill' any Docker containers which are still running from your previous attempts before trying again: `docker stop $(docker ps -aq)` then `docker rm $(docker ps -aq)`.

**Comment by SinTan1071** [comment]
So, Is there any other options except buying a new MAC? I am sooooo poor, I don't think I can afford another one. 😔

**Comment by ChaitanyaKonda** [comment]
@SinTan1071 
Some ways to handle this,
- running burn trusted setup on another laptop with bigger RAM by calling command `npm run setup -- -i gm17/ft-burn/` from 'zkp' folder and copying files under the path `zkp/code/gm17/ft-burn` from this laptop to your personal laptop. 
- Using a cloud VM with bigger RAM config
- Asking somebody else who did a trusted setup of burn to share files under `zkp/code/gm17/ft-burn`
