### ISSUE TITLE
Missing vkIDs.json

### ISSUE THREAD

**Issue by Tulun** [EYBlockchain/nightfall#371]
# Description
When running `npm run test` I get the following error:
zkp_1                | (node:45) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open './src/vkIds.json'
zkp_1                | (node:45) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

#### System information

Docker version: `docker version`
OS & Version: OSX 10.5.2
Commit hash : (if `develop`)

#### Expected behaviour

Tests complete
#### Actual behaviour

Errors out
#### Steps to reproduce the behaviour

1) Create new instance of nightfall from scratch from current master (cloned this Jan 20th, 2020)
2) Run the dockerized containers
3) npm run test

#### Backtrace

````
[backtrace]
````

#### Logs

zkp_1                | (node:45) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open './src/vkIds.json'
zkp_1                | (node:45) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
````
[logs]
````

**Comment by Tulun** [comment]
I get this bug when I run ./nightfall script:

zkp_1                | debug:
zkp_1                | Response from merkle-tree microservice for NFTokenShield:
zkp_1                | debug: filter started
zkp_1                | (node:56) UnhandledPromiseRejectionWarning: Error: Error while loading VKs
zkp_1                |     at initializeVks (/app/src/vk-controller.js:55:11)
zkp_1                | (node:56) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
zkp_1                | (node:56) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Tulun** [comment]
Further, seems to be an issue with the ./nightfall-generate-trusted-setup script.

➜  nightfall git:(master) ./nightfall-generate-trusted-setup

~/Desktop/projects/nightfall/zkp/code/gm17 ~/Desktop/projects/nightfall
~/Desktop/projects/nightfall
*** List of trusted setups ***
1 ft-batch-transfer
2 ft-burn
3 ft-mint
4 ft-transfer
5 nft-burn
6 nft-mint
7 nft-transfer

Do you want to generate all trusted setups? (y/n) : y

> nightfall@1.0.0 setupAll /Users/wc416el/Desktop/projects/nightfall
> docker-compose run zkp npm run setup-all

Starting nightfall_ganache_1           ... done
Starting nightfall_mongo-merkle-tree_1 ... done
Starting nightfall_merkle-tree_1       ... done

> zkp@1.0.0 setup-all /app
> yes | NODE_ENV=setup babel-node code/index.js

The '-f' option has not been specified.
That's OK, we can go ahead and loop through every .code file.
HOWEVER, if you wanted to choose just one file, cancel this process, and instead use option -f (see the README-trusted-setup)
Be warned, this could take up to an hour!
? Continue? y
info: Setup for directory /app/code/gm17/ft-batch-transfer
info: Compiling /app/code/gm17/ft-batch-transfer/ft-batch-transfer.code
debug: Compile output: Compiling /app/code/gm17/ft-batch-transfer/ft-batch-transfer.code


info: Finished compiling at /app/code/gm17/ft-batch-transfer
info: Running setup on /app/code/gm17/ft-batch-transfer
Error: Trusted setup failed: Error: Setup input file(s) not found
    at main (/app/code/index.js:55:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zkp@1.0.0 setup-all: `yes | NODE_ENV=setup babel-node code/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zkp@1.0.0 setup-all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-21T23_40_25_943Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nightfall@1.0.0 setupAll: `docker-compose run zkp npm run setup-all`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nightfall@1.0.0 setupAll script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wc416el/.npm/_logs/2020-01-21T23_40_26_855Z-debug.log
