### ISSUE TITLE
Concurrent transfer commitment issue for fungible and non-fungible tokens

### ISSUE THREAD

**Issue by vishnusudarshan** [EYBlockchain/nightfall#374]
# Description

While transferring fungible and non-fungible token commitments concurrently between accounts is failing. The `POST` requests `/transferNFTCommitment` and `/transferFTCommitment` are returning `VM Exception while processing transaction: revert The proof has not been verified by the contract -- Reason given: The proof has not been verified by the contract` error.

#### Screenshot

<img width="1281" alt="Screenshot 2020-01-23 at 3 35 32 PM" src="https://user-images.githubusercontent.com/38682769/72977186-faacc880-3df9-11ea-9bae-229c1d0110a1.png">

#### Logs

````
POST:/transferNFTCommitment
    {"error":"Returned error: VM Exception while processing transaction: revert The proof has not been verified by the contract -- Reason given: The proof has not been verified by the contract."}
    {
 "errorStack": [
  "Error: Returned error: VM Exception while processing transaction: revert The proof has not been verified by the contract -- Reason given: The proof has not been verified by the contract.",
  "    at Object.ErrorResponse (/app/node_modules/web3-core-helpers/src/errors.js:29:16)",
  "    at Object.<anonymous> (/app/node_modules/web3-core-requestmanager/src/index.js:140:36)",
  "    at /app/node_modules/web3/node_modules/web3-providers-ws/src/index.js:121:44",
  "    at Array.forEach (<anonymous>)",
  "    at W3CWebSocket.WebsocketProvider.connection.onmessage (/app/node_modules/web3/node_modules/web3-providers-ws/src/index.js:98:36)",
  "    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/app/node_modules/yaeti/lib/EventTarget.js:107:17)",
  "    at W3CWebSocket.onMessage (/app/node_modules/web3/node_modules/web3-providers-ws/node_modules/websocket/lib/W3CWebSocket.js:234:14)",
  "    at WebSocketConnection.<anonymous> (/app/node_modules/web3/node_modules/web3-providers-ws/node_modules/websocket/lib/W3CWebSocket.js:205:19)",
  "    at WebSocketConnection.emit (events.js:193:13)",
  "    at WebSocketConnection.processFrame (/app/node_modules/web3/node_modules/web3-providers-ws/node_modules/websocket/lib/WebSocketConnection.js:552:26)",
  "    at /app/node_modules/web3/node_modules/web3-providers-ws/node_modules/websocket/lib/WebSocketConnection.js:321:40",
  "    at processTicksAndRejections (internal/process/task_queues.js:79:9)",
  "    at runNextTicks (internal/process/task_queues.js:56:3)",
  "    at processImmediate (internal/timers.js:416:9)"
 ]
}
    {"body":{"owner":{"name":"liju","publicKey":"0x0ac88fe5ae755710360b19d24454d9861eb593ffe421fed57a8077054ede19ed"},"_id":"5e296cd88e111d0039f10ce3","tokenUri":"samplecoin","tokenId":"0x16b1ac7cae3f1000000000000000000000000000000000000000000000000000","salt":"0x36211731655a161473c5313e5f01cb433241f01dc3ce87ae0fe2567aff7e710d","commitment":"0x974d257e5a9bb4c732392bb758fa8dd1800b5e9229afc159b85eee48b99eb71a","commitmentIndex":0,"isMinted":true,"createdAt":"2020-01-23T09:52:24.901Z","updatedAt":"2020-01-23T09:52:24.901Z","__v":0,"sender":{"secretKey":"0x366a78525ea4dc6b6e1f0d3c2cd0bb6e98051d5283c45e7379cc9adc07944922"},"receiver":{"name":"vishnu","publicKey":"0xd93ce51e80340d4964321f12bc0512bbd2dd94f6e1b8f90a35ae372a36484c86"}}}
    {"params":{}}
    {"query":{}}
  
{
  "reason": "The proof has not been verified by the contract"
}
api-gateway_1        | [object Object]
[object Object]
POST:/transferNFTCommitment
    {"error":"Returned error: VM Exception while processing transaction: revert The proof has not been verified by the contract -- Reason given: The proof has not been verified by the contract."}
    {
 "errorStack": [
  "Error: Returned error: VM Exception while processing transaction: revert The proof has not been verified by the contract -- Reason given: The proof has not been verified by the contract.",
  "    at Object.ErrorResponse (/app/node_modules/web3-core-helpers/src/errors.js:29:16)",
  "    at Object.<anonymous> (/app/node_modules/web3-core-requestmanager/src/index.js:140:36)",
  "    at /app/node_modules/web3/node_modules/web3-providers-ws/src/index.js:121:44",
  "    at Array.forEach (<anonymous>)",
  "    at W3CWebSocket.WebsocketProvider.connection.onmessage (/app/node_modules/web3/node_modules/web3-providers-ws/src/index.js:98:36)",
  "    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/app/node_modules/yaeti/lib/EventTarget.js:107:17)",
  "    at W3CWebSocket.onMessage (/app/node_modules/web3/node_modules/web3-providers-ws/node_modules/websocket/lib/W3CWebSocket.js:234:14)",
  "    at WebSocketConnection.<anonymous> (/app/node_modules/web3/node_modules/web3-providers-ws/node_modules/websocket/lib/W3CWebSocket.js:205:19)",
  "    at WebSocketConnection.emit (events.js:193:13)",
  "    at WebSocketConnection.processFrame (/app/node_modules/web3/node_modules/web3-providers-ws/node_modules/websocket/lib/WebSocketConnection.js:552:26)",
  "    at /app/node_modules/web3/node_modules/web3-providers-ws/node_modules/websocket/lib/WebSocketConnection.js:321:40",
  "    at processTicksAndRejections (internal/process/task_queues.js:79:9)"
 ]
}
    {"body":{"owner":{"name":"vishnu","publicKey":"0xd93ce51e80340d4964321f12bc0512bbd2dd94f6e1b8f90a35ae372a36484c86"},"_id":"5e296dec8e111d0039f10cf0","tokenUri":"propcoin","tokenId":"0xc667e1d07a050000000000000000000000000000000000000000000000000000","salt":"0x5c06ecb53c691b6ba24caff439ff2a2cacbed0ad770d51eaf3c7f727618d5cf7","commitment":"0x03adf5fe135d849d73cf03611e5c29d25e955b1e0ba0259196c5f9801c6b9e43","commitmentIndex":2,"isReceived":true,"commitmentReconciles":true,"commitmentExistsOnchain":true,"createdAt":"2020-01-23T09:57:00.813Z","updatedAt":"2020-01-23T09:57:00.813Z","__v":0,"sender":{"secretKey":"0xeaa96fe9c99e2cfe6ba1418b3da383ee2afacb73b6a5979e2661875bfc04862a"},"receiver":{"name":"duncan","publicKey":"0x46270f6fa89fdec6cc6f731967294fb5bf6a04c479cd866e649effc08c707b02"}}}
    {"params":{}}
    {"query":{}}
  
{
  "reason": "The proof has not been verified by the contract"
}
````

**Comment by LijuJoseJJ** [comment]
we found out the causing issue, changes need to be done are
```
@@ -288,15 +288,15 @@ async function transfer(
     new Element(outputCommitment, 'field'),
   ]);
 
-  await zokrates.computeWitness(codePath, outputDirectory, witnessName, allInputs);
+  await zokrates.computeWitness(codePath, outputDirectory, `${commitment}-${witnessName}`, allInputs);
 
-  await zokrates.generateProof(pkPath, codePath, `${outputDirectory}/witness`, provingScheme, {
+  await zokrates.generateProof(pkPath, codePath, `${outputDirectory}/${commitment}-witness`, provingScheme, {
     createFile: createProofJson,
     directory: outputDirectory,
-    fileName: proofName,
+    fileName: `${commitment}-${proofName}`,
   });
 
-  let { proof } = JSON.parse(fs.readFileSync(`${outputDirectory}/${proofName}`));
+  let { proof } = JSON.parse(fs.readFileSync(`${outputDirectory}/${commitment}-${proofName}`));
```
for operations such as commitment transfer, burn and batch-transfer.

_Explanation: two concurrent call is referring to same file to write and read, which is causing unexpectedly overwritten values for each call._ 

_solution: referred and generated files ('witness' & 'proof.json') should be unique for each api concurrent call.
Suggestion: append commitment value to the generated file names_

**Comment by Westlad** [comment]
Merged in Nightlite
