### ISSUE TITLE
Issue while account creation after a login failure

### ISSUE THREAD

**Issue by vishnusudarshan** [EYBlockchain/nightfall#396]
# Description

The users are not able to create an account with their unique username and password after they met with a login failure because of the invalid username and password.   

#### System information

Docker version: `docker version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour

Users should be able to create an account even after a login failure.

#### Screenshot

<img width="762" alt="Screenshot 2020-02-28 at 4 10 26 PM" src="https://user-images.githubusercontent.com/38682769/75544307-b55b6680-5a49-11ea-8734-7f683b8b6457.png">

#### Steps to reproduce the behaviour

- Try to login with an invalid username and password (username not registered yet)
- Try to create an account

#### Logs

````
database_1           | error: POST:/users
database_1           |     {"error":"Command failed: mongo nightfall --host=mongo-nightfall -u admin -p admin setup-mongo-acl-for-new-users.js\n"}
database_1           |     {
database_1           |  "errorStack": [
database_1           |   "Error: Command failed: mongo nightfall --host=mongo-nightfall -u admin -p admin setup-mongo-acl-for-new-users.js",
database_1           |   "",
database_1           |   "    at ChildProcess.exithandler (child_process.js:299:12)",
database_1           |   "    at ChildProcess.emit (events.js:193:13)",
database_1           |   "    at maybeClose (internal/child_process.js:999:16)",
database_1           |   "    at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)"
database_1           |  ]
database_1           | }
database_1           |     {"body":{"name":"vishnu","email":"vishnu@ey.com","password":"1234","address":"0x52e2DAcd505f68048d88DfF2eE103D2C912e927d"}}
database_1           |     {"params":{}}
database_1           |     {"query":{}}
database_1           |   
database_1           | [object Object]
api-gateway_1        | { code: 253,
api-gateway_1        |   message:
api-gateway_1        |    'Command failed: mongo nightfall --host=mongo-nightfall -u admin -p admin setup-mongo-acl-for-new-users.js\n',
api-gateway_1        |   errorStack:
api-gateway_1        |    'Error: Command failed: mongo nightfall --host=mongo-nightfall -u admin -p admin setup-mongo-acl-for-new-users.js\n\n    at ChildProcess.exithandler (child_process.js:299:12)\n    at ChildProcess.emit (events.js:193:13)\n    at maybeClose (internal/child_process.js:999:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)' }
api-gateway_1        | [object Object]
````

**Comment by LijuJoseJJ** [comment]
doesn't seem to appear in latest master
