### ISSUE TITLE
API-gateway start failed

### ISSUE THREAD

**Issue by xuchenhao001** [EYBlockchain/nightfall#48]
# Description

I am trying to run zkp-demo on my host following the README.md at version `1.0.2` (which is the newest tag for now). And I got api-gate-way started failed with errors (I have replaced `docker-proxy` with `dotdocker`):
```bash

> api-gateway@0.0.1 start /app
> NODE_ENV=LOCAL nodemon --exec babel-node ./src/index.js

[nodemon] 1.19.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `babel-node ./src/index.js`
internal/modules/cjs/loader.js:670
    throw err;
    ^

Error: Cannot find module '/app/src/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at Object.<anonymous> (/app/node_modules/@babel/node/lib/_babel-node.js:234:23)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
[nodemon] app crashed - waiting for file changes before starting...
nightfall_truffle-offchain_1 exited with code 1
```
After have a deep look into the container, I found that the directory `src` is empty. And I found that there is another `api-gateway` directory besides `API-Gateway`, which means that `api-gateway` container mounts a wrong directory.

```bash
~/nightfall$ ls
accounts     contributing.md     docker-entrypoint-initdb.d  node_modules       README.md            UI.md
api-gateway  database            license.md                  offchain           SECURITY.md          zkp
API-Gateway  doc                 limitations.md              package.json       security-updates.md  zkp-demo
config       docker-compose.yml  Makefile                    package-lock.json  ui                   zkp-utils
```
And after I correctly copied `API-Gateway/src` into `api-gateway/src`, I got another error here:
```bash
> api-gateway@0.0.1 start /app
> NODE_ENV=LOCAL nodemon --exec babel-node ./src/index.js

[nodemon] 1.19.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `babel-node ./src/index.js`
fs.js:119
    throw err;
    ^

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:514:3)
    at tryReadSync (fs.js:337:20)
    at Object.readFileSync (fs.js:374:19)
    at /app/node_modules/@babel/core/lib/config/files/utils.js:29:39
    at cachedFunction (/app/node_modules/@babel/core/lib/config/caching.js:33:19)
    at readConfig (/app/node_modules/@babel/core/lib/config/files/configuration.js:176:8)
    at config.reduce (/app/node_modules/@babel/core/lib/config/files/configuration.js:105:24)
    at Array.reduce (<anonymous>)
    at findRelativeConfig (/app/node_modules/@babel/core/lib/config/files/configuration.js:102:56)
    at buildRootChain (/app/node_modules/@babel/core/lib/config/config-chain.js:113:39)
[nodemon] app crashed - waiting for file changes before starting...
```
And I don't know how to solve this problem. Please give me some help. Thanks!

#### System information

Docker version: `18.09.2`
OS & Version: Linux (Ubuntu 16.04)
Commit hash : df0ff8bf056a8a1d5dbf718c0c42cbc916fea785 (v1.0.2)

#### Expected behaviour
Open browser, and successfully login to `ZKP Demo`

#### Actual behaviour
Tried to registe a new user and got:
```bash
http://api.nightfall.docker/createAccount
502 BAD GATEWAY
```

#### Steps to reproduce the behaviour
According to README.md until `./zkp-demo` step.

**Comment by asishap** [comment]
@xuchenhao001 
This issue is related to docker-proxy in Linux distribution. Already raised a ticket for that issue. Please check the status over there.

Linking to that ticket #20

**Comment by cmumby** [comment]
@xuchenhao001 in `api-gateway/`  can you check if  ```.babelrc``` was copied as a directory? If so you can remove that directory and replace it a `.babelrc` file that has:
```{
  "presets": [
    ["@babel/preset-env", {
      "targets": {
        "node": "11.15"
      }
    }]
  ]
}
```
This should get rid of the `Error: EISDIR: illegal operation on a directory, read` you encountered.
