### ISSUE TITLE
Tests fail with dot docker

### ISSUE THREAD

**Issue by iAmMichaelConnor** [EYBlockchain/nightfall#86]
# Description
I notice the README now says to use dotdocker, so I ran all tests (`./zkp-demo-test`) on the Master branch using dotdocker. The tests failed.

The tests passed with docker-proxy.

#### System information

Docker version: `docker version`
OS & Version: OSX
Branch: Master

#### Expected behaviour
Tests should all pass

#### Actual behaviour
Tests failed with dotdocker

#### Steps to reproduce the behaviour
Run the tests with dotdocker

#### Backtrace

````
ZoKrates running with Nodejs environment test
zkp_test_1               |     Running the container; mounted: nightfall_zkp_code_test:/home/zokrates/code/:cached
zkp_test_1               |     { Error: (HTTP code 500) server error - OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/docker/volumes/nightfall_zkp_code_test/_data\\\" to rootfs \\\"/var/lib/docker/overlay2/52ec64705012323d0fbfac60f0d8e14707a7390fdfdb856ce9987caf21d5af0f/merged\\\" at \\\"/var/lib/docker/overlay2/52ec64705012323d0fbfac60f0d8e14707a7390fdfdb856ce9987caf21d5af0f/merged/home/zokrates/code\\\" caused \\\"no such file or directory\\\"\"": unknown 
zkp_test_1               |         at /app/node_modules/docker-modem/lib/modem.js:239:17
zkp_test_1               |         at getCause (/app/node_modules/docker-modem/lib/modem.js:269:7)
zkp_test_1               |         at Modem.buildPayload (/app/node_modules/docker-modem/lib/modem.js:238:5)
zkp_test_1               |         at IncomingMessage.<anonymous> (/app/node_modules/docker-modem/lib/modem.js:214:14)
zkp_test_1               |         at IncomingMessage.emit (events.js:198:15)
zkp_test_1               |         at endReadableNT (_stream_readable.js:1139:12)
zkp_test_1               |         at processTicksAndRejections (internal/process/task_queues.js:81:17)
zkp_test_1               |       reason: 'server error',
zkp_test_1               |       statusCode: 500,
zkp_test_1               |       json:
zkp_test_1               |        { message:
zkp_test_1               |           'OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \\"rootfs_linux.go:58: mounting \\\\\\"/var/lib/docker/volumes/nightfall_zkp_code_test/_data\\\\\\" to rootfs \\\\\\"/var/lib/docker/overlay2/52ec64705012323d0fbfac60f0d8e14707a7390fdfdb856ce9987caf21d5af0f/merged\\\\\\" at \\\\\\"/var/lib/docker/overlay2/52ec64705012323d0fbfac60f0d8e14707a7390fdfdb856ce9987caf21d5af0f/merged/home/zokrates/code\\\\\\" caused \\\\\\"no such file or directory\\\\\\"\\"": unknown' } }
api-gateway_test_1       | error: POST:/coin/mint
api-gateway_test_1       |         {}
api-gateway_test_1       |         {"body":{"A":"0x00000000000000000000000000000003","commitmentIndex":1,"commitment":"0x194fcfef7c5190cf740119cacaa572911621bd2d2f54a8e0ff7798"}}
api-gateway_test_1       |         {"params":{}}
api-gateway_test_1       |         {"query":{}}
api-gateway_test_1       |     
mongo_test_1             | 2019-07-23T10:38:49.766+0000 I NETWORK  [conn8] end connection 172.19.0.11:49308 (6 connections now open)
mongo_test_1             | 2019-07-23T10:38:49.784+0000 I NETWORK  [conn4] end connection 172.19.0.11:49270 (5 connections now open)
mongo_test_1             | 2019-07-23T10:38:49.796+0000 I NETWORK  [conn9] end connection 172.19.0.11:49328 (3 connections now open)
mongo_test_1             | 2019-07-23T10:38:49.805+0000 I NETWORK  [conn1] end connection 172.19.0.11:49248 (4 connections now open)
mongo_test_1             | 2019-07-23T10:38:49.835+0000 I NETWORK  [conn2] end connection 172.19.0.11:49266 (2 connections now open)
mongo_test_1             | 2019-07-23T10:38:49.874+0000 I NETWORK  [conn5] end connection 172.19.0.11:49272 (1 connection now open)
mongo_test_1             | 2019-07-23T10:38:50.069+0000 I NETWORK  [conn3] end connection 172.19.0.11:49268 (0 connections now open)
nightfall_api-gateway_test_1 exited with code 137
````

**Comment by iAmMichaelConnor** [comment]
Suggest we either fix dotdocker, or edit the README (back to recommending docker-proxy) until it is fixed

**Comment by ocgordon** [comment]
Could this have something to do with your setup @iAmMichaelConnor ? I just ran from master with dotdocker, and couldn't replicate this error.

**Comment by iAmMichaelConnor** [comment]
This issue didn't persist. All tests ran on my most recent attempt. Not sure what went wrong. Will close the issue. If it reappears, another issue will appear.
